import type { Client, Lead, Invoice, Receipt, TeamMember, Message } from '@/types';

export const seedClients: Client[] = [
  {
    id: 'c1',
    name: 'Acme Logistics',
    email: 'contact@acmelogistics.com',
    phone: '+233 20 123 4567',
    type: 'Enterprise',
    status: 'Active',
    lastContact: '2 days ago',
    createdAt: '2024-01-15',
  },
  {
    id: 'c2',
    name: 'Bright Schools',
    email: 'admin@brightschools.edu.gh',
    phone: '+233 24 987 6543',
    type: 'School',
    status: 'Active',
    lastContact: '1 week ago',
    createdAt: '2024-02-01',
  },
  {
    id: 'c3',
    name: 'City Health Clinic',
    email: 'info@cityhealth.com',
    phone: '+233 27 456 7890',
    type: 'Healthcare',
    status: 'Prospect',
    lastContact: '3 days ago',
    createdAt: '2024-02-20',
  },
  {
    id: 'c4',
    name: 'Nexus SME Hub',
    email: 'hello@nexussme.com',
    phone: '+233 26 789 0123',
    type: 'SME',
    status: 'Lead',
    lastContact: 'Today',
    createdAt: '2024-03-01',
  },
  {
    id: 'c5',
    name: 'TechStart Ghana',
    email: 'team@techstart.io',
    phone: '+233 23 345 6789',
    type: 'SME',
    status: 'Active',
    lastContact: '5 days ago',
    createdAt: '2024-01-20',
  },
  {
    id: 'c6',
    name: 'Royal Hospital',
    email: 'admin@royalhospital.org',
    phone: '+233 28 901 2345',
    type: 'Healthcare',
    status: 'Prospect',
    lastContact: '1 week ago',
    createdAt: '2024-02-28',
  },
];

export const seedLeads: Lead[] = [
  {
    id: 'l1',
    name: 'Kwame Asante',
    company: 'Golden Farms Ltd',
    email: 'kwame@goldenfarms.com',
    value: 8500,
    stage: 'New',
    temperature: 'Hot',
    createdAt: '2024-03-25',
    updatedAt: '2024-03-25',
  },
  {
    id: 'l2',
    name: 'Abena Owusu',
    company: 'Sunrise Academy',
    email: 'abena@sunrise.edu',
    value: 12000,
    stage: 'Contacted',
    temperature: 'Warm',
    createdAt: '2024-03-20',
    updatedAt: '2024-03-22',
  },
  {
    id: 'l3',
    name: 'Kofi Mensah',
    company: 'Mensah Enterprises',
    email: 'kofi@mensahent.com',
    value: 5500,
    stage: 'Qualified',
    temperature: 'Hot',
    createdAt: '2024-03-15',
    updatedAt: '2024-03-24',
  },
  {
    id: 'l4',
    name: 'Efua Darko',
    company: 'Wellness Center GH',
    email: 'efua@wellnessgh.com',
    value: 4200,
    stage: 'Proposal Sent',
    temperature: 'Warm',
    createdAt: '2024-03-10',
    updatedAt: '2024-03-23',
  },
  {
    id: 'l5',
    name: 'Yaw Boateng',
    company: 'Boateng Logistics',
    email: 'yaw@boatenglog.com',
    value: 15000,
    stage: 'Won',
    temperature: 'Hot',
    createdAt: '2024-02-28',
    updatedAt: '2024-03-20',
  },
  {
    id: 'l6',
    name: 'Ama Serwaa',
    company: 'Serwaa Designs',
    email: 'ama@serwaadesigns.com',
    value: 3200,
    stage: 'Lost',
    temperature: 'Cold',
    createdAt: '2024-02-15',
    updatedAt: '2024-03-01',
  },
  {
    id: 'l7',
    name: 'Daniel Osei',
    company: 'Osei Consultancy',
    email: 'daniel@oseiconsult.com',
    value: 7800,
    stage: 'New',
    temperature: 'Warm',
    createdAt: '2024-03-26',
    updatedAt: '2024-03-26',
  },
  {
    id: 'l8',
    name: 'Grace Addo',
    company: 'Addo Pharmacy',
    email: 'grace@addopharm.com',
    value: 6500,
    stage: 'Contacted',
    temperature: 'Hot',
    createdAt: '2024-03-18',
    updatedAt: '2024-03-21',
  },
];

export const seedInvoices: Invoice[] = [
  {
    id: 'inv1',
    clientId: 'c1',
    clientName: 'Acme Logistics',
    invoiceNumber: 'INV-2041',
    items: [
      { id: 'i1', description: 'Website Development', quantity: 1, unitPrice: 5000 },
      { id: 'i2', description: 'SEO Optimization', quantity: 3, unitPrice: 500 },
    ],
    subtotal: 6500,
    taxRate: 15,
    taxAmount: 975,
    total: 7475,
    status: 'Paid',
    issueDate: '2024-03-01',
    dueDate: '2024-03-15',
    paidDate: '2024-03-10',
  },
  {
    id: 'inv2',
    clientId: 'c2',
    clientName: 'Bright Schools',
    invoiceNumber: 'INV-2042',
    items: [
      { id: 'i3', description: 'School Management System', quantity: 1, unitPrice: 3200 },
    ],
    subtotal: 3200,
    taxRate: 15,
    taxAmount: 480,
    total: 3680,
    status: 'Sent',
    issueDate: '2024-03-10',
    dueDate: '2024-03-24',
  },
  {
    id: 'inv3',
    clientId: 'c3',
    clientName: 'City Health Clinic',
    invoiceNumber: 'INV-2043',
    items: [
      { id: 'i4', description: 'Branding Package', quantity: 1, unitPrice: 1800 },
      { id: 'i5', description: 'Social Media Setup', quantity: 1, unitPrice: 400 },
    ],
    subtotal: 2200,
    taxRate: 15,
    taxAmount: 330,
    total: 2530,
    status: 'Overdue',
    issueDate: '2024-02-20',
    dueDate: '2024-03-05',
  },
  {
    id: 'inv4',
    clientId: 'c5',
    clientName: 'TechStart Ghana',
    invoiceNumber: 'INV-2044',
    items: [
      { id: 'i6', description: 'Mobile App Development', quantity: 1, unitPrice: 8500 },
      { id: 'i7', description: 'UI/UX Design', quantity: 1, unitPrice: 2500 },
    ],
    subtotal: 11000,
    taxRate: 15,
    taxAmount: 1650,
    total: 12650,
    status: 'Draft',
    issueDate: '2024-03-25',
    dueDate: '2024-04-08',
  },
];

export const seedReceipts: Receipt[] = [
  {
    id: 'r1',
    invoiceId: 'inv1',
    receiptNumber: 'RCP-1001',
    clientName: 'Acme Logistics',
    amount: 7475,
    paymentDate: '2024-03-10',
    paymentMethod: 'Bank Transfer',
    generatedAt: '2024-03-10',
  },
];

export const seedTeam: TeamMember[] = [
  {
    id: 't1',
    name: 'Ama Darko',
    role: 'Designer',
    email: 'ama@zentrio.io',
    status: 'Active',
    tasks: [
      { id: 'task1', title: 'Update brand kit', status: 'In Progress', assignedAt: '2024-03-20' },
      { id: 'task2', title: 'Social media assets', status: 'Pending', assignedAt: '2024-03-25' },
    ],
  },
  {
    id: 't2',
    name: 'Kojo Boateng',
    role: 'Developer',
    email: 'kojo@zentrio.io',
    status: 'Active',
    tasks: [
      { id: 'task3', title: 'API integration', status: 'In Progress', assignedAt: '2024-03-22' },
      { id: 'task4', title: 'Invoice module', status: 'Completed', assignedAt: '2024-03-15' },
    ],
  },
  {
    id: 't3',
    name: 'Efua Thompson',
    role: 'Intern',
    email: 'efua@zentrio.io',
    status: 'Away',
    tasks: [
      { id: 'task5', title: 'Lead research', status: 'Pending', assignedAt: '2024-03-26' },
      { id: 'task6', title: 'Client onboarding docs', status: 'In Progress', assignedAt: '2024-03-24' },
    ],
  },
  {
    id: 't4',
    name: 'Kwesi Mensah',
    role: 'Manager',
    email: 'kwesi@zentrio.io',
    status: 'Active',
    tasks: [
      { id: 'task7', title: 'Q3 planning', status: 'Pending', assignedAt: '2024-03-27' },
    ],
  },
];

export const seedMessages: Message[] = [
  {
    id: 'm1',
    author: 'Spirit',
    authorRole: 'Operations',
    content: 'Q3 planning starts Monday. Please update your task boards by Friday.',
    timestamp: '2024-03-26T09:00:00',
    isPinned: true,
  },
  {
    id: 'm2',
    author: 'Spirit',
    authorRole: 'Operations',
    content: 'New client onboarding checklist added to the shared drive.',
    timestamp: '2024-03-25T14:30:00',
    isPinned: false,
  },
  {
    id: 'm3',
    author: 'Spirit',
    authorRole: 'Operations',
    content: 'Invoice template updated—use v3 for all new invoices.',
    timestamp: '2024-03-24T11:15:00',
    isPinned: false,
  },
  {
    id: 'm4',
    author: 'Spirit',
    authorRole: 'Operations',
    content: 'Team lunch this Friday at 1 PM. Please confirm attendance.',
    timestamp: '2024-03-23T16:00:00',
    isPinned: false,
  },
];
