"""add invoice items, payments, receipts, invoice counter

Revision ID: 52dfc1df2de2
Revises: 1d2e03bc1242
Create Date: 2026-09-19 13:56:14.357662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dfc1df2de2'
down_revision = '1d2e03bc1242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('singleton', sa.Boolean(), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('receipt_prefix', sa.String(length=20), nullable=False),
    sa.Column('next_receipt_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id'),
    sa.UniqueConstraint('receipt_number')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('paid_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_rate_snapshot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_enabled_snapshot', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('tax_enabled_snapshot')
        batch_op.drop_column('tax_rate_snapshot')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('paid_date')
        batch_op.drop_column('issue_date')

    op.drop_table('receipt')
    op.drop_table('payment')
    op.drop_table('invoice_item')
    op.drop_table('invoice_counter')
    # ### end Alembic commands ###
